#!/usr/bin/env node
var check = require('./lib/check-integration-env');

if (process.argv.length <= 2) {
	process.stderr.write('Usage: check-integration-env path/to/services.yaml [--debug=true]\n');
	process.exit(1);
}

var config = process.argv[2];

if (process.argv.length >= 4 &&
    process.argv[3] === '--debug=true') {
	DEBUG = true;
}

check(config, function(err, result) {
    if (err) {
        console.log('ERROR: ' + err);
    } else {
        console.log('GOOD: ' + result.good.join(' ,'));
        console.log('BAD: ' + result.bad.join(' ,'));
    }
});
